packages:
    - 'SciFlow'
    - 'SciFlow-drmaa'
    - 'SciFlow-viz'

extra-deps:
    - drmaa-0.3.0
    - distributed-process-monad-control-0.5.1.3

    - git:     https://github.com/haskell-distributed/distributed-static.git
      commit:  b7591922edafb0203d8ef4c39a724ff0553327da

    - git:     https://github.com/haskell-distributed/network-transport-tcp.git
      commit:  d58250e2388b86a1865ac4139373cbdc106e72e1

    - git:     https://github.com/haskell-distributed/distributed-process.git
      commit:  660d554f6acd2dba8b605c84e8fa69e45708bc14

resolver: nightly-2019-05-22