packages:
    - 'SciFlow'
    - 'SciFlow-remote'
    - 'SciFlow-app'

extra-deps:
    - distributed-process-monad-control-0.5.1.3
    - network-transport-tcp-0.8.0
    - jmacro-0.6.17
    - distributed-static-0.3.9
    #- git:     https://github.com/haskell-distributed/distributed-process.git
    #  commit:  660d554f6acd2dba8b605c84e8fa69e45708bc14
    - git:     https://github.com/patrickt/distributed-process.git
      commit:  645bc55c1b0b0d18227d1fc093379967c74af669
 

allow-newer: true

resolver: lts-17.5
