packages:
    - 'SciFlow'
    - 'SciFlow-remote'
    - 'SciFlow-app'

extra-deps:
    - distributed-process-monad-control-0.5.1.3
    - network-transport-tcp-0.8.0
    - jmacro-0.6.17.1
    - distributed-static-0.3.9
    - git:     https://github.com/haskell-distributed/distributed-process.git
      commit:  8de080874b7671186af8dc04deb471e909b10719
 

allow-newer: true

resolver: lts-19.19
