packages:
    - 'SciFlow'
    - 'SciFlow-remote'
    - 'SciFlow-app'

extra-deps:
    - drmaa-0.3.0
    - distributed-process-monad-control-0.5.1.3
    - network-transport-tcp-0.7.0
    - jmacro-0.6.16
    - distributed-static-0.3.9
    - git:     https://github.com/haskell-distributed/distributed-process.git
      commit:  660d554f6acd2dba8b605c84e8fa69e45708bc14

resolver: nightly-2019-05-22
#resolver: lts-15.0
